spring:
  profiles:
    active: startDev,infrDev
  application:
    name: order-demo
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.dsy.order.gateway.database: debug
  config: classpath:logback-spring.xml