spring:
  profiles:
    active: startDev,infrDev
  application:
    name: order-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  config: classpath:logback-spring.xml
mybatis:
  configuration:
    log-impl: com.dsy.order.config.MybatisLogger